# Make a container capable of running RAMCloud using the locally built RAMCloud binaries and libraries.
FROM debian:buster
RUN apt-get update \
 && apt-get install --yes \
      libboost-filesystem1.67.0 \
      libboost-program-options1.67 \
      libboost-system1.67.0 \
      libibverbs1 \
      libpcrecpp0v5 \
      libprotobuf17 \
      libssl1.1 \
      libzookeeper-mt2 \
 && rm -rf /var/lib/apt/lists/*
COPY ./RAMCloud/install /usr/local
