#!/bin/bash -eux
# Obtains the patched RAMCloud code by cloning the official RAMCloud repo at the appropriate changeset and applying the
# Stateless patch set on top of it.

PROJECT_SRC="$(readlink --canonicalize "$(dirname "$0")/..")"
cd "${PROJECT_SRC}"
git clone https://github.com/PlatformLab/RAMCloud.git
cd RAMCloud
[[ -n $(git config user.name) ]] || git config user.name "nobody"
[[ -n $(git config user.email) ]] || git config user.email "nobody@nowhere"
git checkout -b stg_patched "$(head -1 ../patches/series | awk '{print $NF}')"
git submodule update --init --recursive
stg init
stg import --series ../patches/series
